export const USER_ROLES = {
  EMPLOYEE: "EMPLOYEE",
  MANAGER: "MANAGER",
};

export const LEAVE_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};

export const LEAVE_TYPES = {
  CASUAL: "CASUAL",
  SICK: "SICK",
  EARNED: "EARNED",
  MATERNITY: "MATERNITY",
  PATERNITY: "PATERNITY",
  UNPAID: "UNPAID",
};